version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      - ./:/usr/src/app
    environment:
      - SSH_AUTH_SOCK=/var/run/docker.sock:/var/run/docker.sock
