version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    environment:
      - SSH_AUTH_SOCK=/var/run/docker.sock:/var/run/docker.sock
