name: Deploy Demo App To My Kubernetes Homelab
on:
  push:
    branches:
      - master
jobs:
  Test-SSH:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      # - name: Configure SSH
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Add SSH private key to agent
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
          USERNAME: ${{ secrets.USERNAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

        run: |
          mkdir -p ~/.ssh
          echo $PRIVATE_KEY > ~/.ssh/id_ed25519
          echo "\n" >> ~/.ssh/id_ed25519
          echo $SUPER_SECRET > ~/.ssh/id_ed25519
          echo "\n" >> ~/.ssh/id_ed25519
          echo $USERNAME > ~/.ssh/id_ed25519
          echo "\n" >> ~/.ssh/id_ed25519
          echo "Debug" > ~/.ssh/id_ed25519
          echo "\n" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 70.71.50.252  >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo $USERNAME
          echo $SUPER_SECRET
          echo "Debug"
          cat ~/.ssh/id_ed25519

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Deploy to server
        run: |
          ssh-keyscan -H 70.71.50.252  >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ls -al ~/.ssh/
          cat  ~/.ssh/id_ed25519
          ssh devops@70.71.50.252 -v "ls -la"
