name: Deploy Demo App To My Kubernetes Homelab
on: [push]
jobs:
  Test-SSH:
    runs-on: ubuntu-latest
    steps:
      - name: Test ssh connection
        run: |
            echo "This is a test"
            echo ${{ secrets.USERNAME }}
            echo ${{ secrets.HOST }}
            ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -v


