name: Deploy Demo App To My Kubernetes Homelab
on:
  push:
    branches:
      - master
jobs:
  Test-SSH:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH private key to agent
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.PRIVATE_KEY }} > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 70.71.50.252  >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     limit-access-to-actor: true 

      - name: Deploy to server
        run: |
          ssh devops@70.71.50.252 -v "ls -la"
